# Generated by Django 4.1.6 on 2023-03-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
